# Generated by Django 3.2 on 2021-05-03 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=180)),
                ('task', models.CharField(max_length=180)),
                ('priority', models.IntegerField(default=1)),
                ('ch_image', models.ImageField(blank=True, default='choreImages/defaultpic.png', upload_to='choreImages')),
                ('isComplete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(blank=True, upload_to='proof')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_images', to='chores.chore')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
