# Generated by Django 3.1.7 on 2021-03-31 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=100)),
                ('dueDate', models.DateField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(default='Home', max_length=200)),
                ('choresCompleted', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(blank=True, default='media/proof/todologo.jpg', upload_to='media/proof')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('chore', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chore_images', to='chores.chore')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
