# Generated by Django 3.1.7 on 2021-03-21 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('task', models.CharField(blank=True, max_length=200)),
                ('dueDate', models.DateField()),
                ('seller', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='choreImages')),
                ('dateCompleted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(upload_to='proof')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_images', to='chores.chore')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
