# Generated by Django 3.1.7 on 2021-04-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='proof',
            field=models.ImageField(blank=True, upload_to='proof'),
        ),
    ]
